### ISSUE TITLE
运行KCObjc target崩溃

### ISSUE THREAD

**Issue by yulongfy** [LGCooci/objc4_debug#12]
运行的是objc4-781工程，报错
mac系统是11.0.1
xcode是12.1

大佬能帮忙分析下是啥问题吗？下面是报错的信息，感谢！

` dyld: Symbol not found: _sel_hash
  Referenced from: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
  Expected in: /Users/xxx/Build/Products/Debug/libobjc.A.dylib
 in /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation`

**Comment by imzhiyuanxiaopo** [comment]
> 运行的是objc4-781工程，报错
> mac系统是11.0.1
> xcode是12.1
> 
> 大佬能帮忙分析下是啥问题吗？下面是报错的信息，感谢！
> 
> ` dyld: Symbol not found: _sel_hash Referenced from: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation Expected in: /Users/xxx/Build/Products/Debug/libobjc.A.dylib in /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation`

我也是这个问题  我查看了一下系统文件  确实11之后比10.15少了这个foundation文件   因为是系统路径  还没有权限手动添加文件  google也没找到解决方案

**Comment by LGCooci** [comment]
现在apple没有更新objc源码  针对大版本更新 无论系统还是xcode版本 都是比较麻烦的! 我编译了一个版本 但是还是有问题 考虑到误导你们的认知 这里就先不提供开源! 我们一起坐等开源新的源码吧😺😺😺
