### ISSUE TITLE
iOS14 _objc_storeWeak crash 有遇到过没？

### ISSUE THREAD

**Issue by ceekay1991** [LGCooci/objc4_debug#14]
kernel_version : Darwin Kernel Version 20.1.0: Fri Oct 30 00:34:15 PDT 2020; root:xnu-7195.42.3~1/RELEASE_ARM64_T8010
process_name : BaiduBoxApp
process_id : 3421
parent_process_id : 1
Exception Codes: #0 at 0x00000001d94cc1f0
Exception Type: SIGABRT
ExtraInfo:{}
Code Type: arm64
OS Version: iPhone OS 14.2 (18B92)
Hardware Model: iPhone9,1
Launch Time: 2021-02-28 23:46:41
Date/Time: 2021-02-28 23:47:10
Thread 0 Crashed:
0    libsystem_kernel.dylib           ___abort_with_payload	(in libsystem_kernel.dylib)	8
1    libsystem_kernel.dylib           _abort_with_payload_wrapper_internal	(in libsystem_kernel.dylib)	0
2    libobjc.A.dylib                  _objc_fatalv(unsigned long long, unsigned long long, char const*, char*)	(in libobjc.A.dylib)	104
3    libobjc.A.dylib                  _objc_fatalv(unsigned long long, unsigned long long, char const*, char*)	(in libobjc.A.dylib)	0
4    libobjc.A.dylib                  _weak_clear_no_lock	(in libobjc.A.dylib)	0
5    libobjc.A.dylib                  _objc_storeWeak	(in libobjc.A.dylib)	348
6    WebKit                           -[WKScriptMessage _initWithBody:webView:frameInfo:name:world:]	(in WebKit)	136
7    WebKit                           ScriptMessageHandlerDelegate::didPostMessage(WebKit::WebPageProxy&, WebKit::FrameInfoData&&, API::ContentWorld&, WebCore::SerializedScriptValue&)	(in WebKit)	204
8    WebKit                           WebKit::WebUserContentControllerProxy::didPostMessage(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long long, IPC::DataReference const&, WTF::CompletionHandler<void (IPC::DataReference const&, WTF::String const&)>&&)	(in WebKit)	532
9    WebKit                           void IPC::handleMessageAsync<Messages::WebUserContentControllerProxy::DidPostMessage, WebKit::WebUserContentControllerProxy, void (WebKit::WebUserContentControllerProxy::*)(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long long, IPC::DataReference const&, WTF::CompletionHandler<void (IPC::DataReference const&, WTF::String const&)>&&)>(IPC::Connection&, IPC::Decoder&, WebKit::WebUserContentControllerProxy*, void (WebKit::WebUserContentControllerProxy::*)(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long long, IPC::DataReference const&, WTF::CompletionHandler<void (IPC::DataReference const&, WTF::String const&)>&&))	(in WebKit)	3232
10   WebKit                           WebKit::WebUserContentControllerProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&)	(in WebKit)	76
11   WebKit                           IPC::MessageReceiverMap::dispatchMessage(IPC::Connection&, IPC::Decoder&)	(in WebKit)	116
12   WebKit                           WebKit::WebProcessProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&)	(in WebKit)	36
13   WebKit                           IPC::Connection::dispatchMessage(std::__1::unique_ptr<IPC::Decoder, std::__1::default_delete<IPC::Decoder> >)	(in WebKit)	596
14   WebKit                           IPC::Connection::dispatchIncomingMessages()	(in WebKit)	492
15   JavaScriptCore                   WTF::RunLoop::performWork()	(in JavaScriptCore)	528
16   JavaScriptCore                   WTF::RunLoop::performWork(void*)	(in JavaScriptCore)	32
17   CoreFoundation                   ___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__	(in CoreFoundation)	24
18   CoreFoundation                   ___CFRunLoopDoSource0	(in CoreFoundation)	204
19   CoreFoundation                   ___CFRunLoopDoSources0	(in CoreFoundation)	256
20   CoreFoundation                   ___CFRunLoopRun	(in CoreFoundation)	776
21   CoreFoundation                   _CFRunLoopRunSpecific	(in CoreFoundation)	572
22   GraphicsServices                 _GSEventRunModal	(in GraphicsServices)	160
23   UIKitCore                        -[UIApplication _run]	(in UIKitCore)	1052
24   UIKitCore                        _UIApplicationMain	(in UIKitCore)	164
25   BaiduBoxApp                      main		(in BaiduBoxApp)	(main.m:28)	24
26   libdyld.dylib                    _start	(in libdyld.dylib)	4

**Comment by Wuhaibin-aaron** [comment]
请问一下，这个有解决的方案吗？

**Comment by LGCooci** [comment]
这个报错是在我的objc-818源码里面报错? 具体运行情况能够复现? 如果这里不方便回复 你可以加我微信: KC_Cooci

**Comment by LGCooci** [comment]
这个问题没有反馈复现和奔溃其他信息  我暂时关闭  如果你还没有解决请加我微信:  KC_Cooci

**Comment by Z-JaDe** [comment]
这个问题，最后有解没。同遇到。没法复现
