### ISSUE TITLE
M1 11.2.1 (20D74)  Xcode  12.4 (12D4e).   源码可以断点，但是main函数什么的不能断点。

### ISSUE THREAD

**Issue by Dcell** [LGCooci/objc4_debug#15]
M1 11.2.1 (20D74)  Xcode  12.4 (12D4e).   源码可以断点，但是main函数什么的不能断点。

**Comment by Dcell** [comment]
额... 发现只能断点，编译顺序中第一个文件，有人碰到过这种问题么。我现在断点只能 把想断点的文件拖到第一个...

**Comment by TheBloodElf** [comment]
@Dcell 怎么解决的？什么叫"发现只能断点，编译顺序中第一个文件"，应该怎么做。

**Comment by Dcell** [comment]
你只能断点 build-phases complile source 里面的第一个文件，如果你要断点其他文件，只能拖拽更改编译顺序。

**Comment by TheBloodElf** [comment]
我发现并不是，你可能是target没有选对，我把target选成KCObjcBuild，run就可以断在KCObjcBuild/main.m文件。

**Comment by Dcell** [comment]
你可以在KCObjcBuild下 再建几个文件，试试断点，新文件的断点

**Comment by LGCooci** [comment]
这个是编译调试的问题! 毕竟objc这个源码是用来调试底层的 所以对上层代码不友好是正常 希望理解 过段时间我会编译一个全工程都能调试的源码
