### ISSUE TITLE
希望博主能加上 CoreFoundation、libdispatch 源码，拜托 🙏🏻

### ISSUE THREAD

**Issue by willokyes** [LGCooci/objc4_debug#17]
同样希望博主能加上 CoreFoundation、libdispatch，拜托：
https://github.com/apple/swift-corelibs-foundation （可编译成功）
https://github.com/apple/swift-corelibs-libdispatch (不可编译成功)

**Comment by LGCooci** [comment]
后期会持续更新!!!
