### ISSUE TITLE
无法进入断点

### ISSUE THREAD

**Issue by chao2318** [LGCooci/objc4_debug#18]
KCObjcBuild[80175:963663] Hello, World! KCObjcBuild was compiled with optimization - stepping may behave oddly; variables may not be available.

目前无法正确的使用断点，感觉整个是乱的，查过相关配置，是debug模式，并且优化等级为None

**Comment by LGCooci** [comment]
KC 重磅提示 调试工程很重要 源码直观就是爽
 ⚠️编译调试不能过: 请你检查以下几小点⚠️
 ①: enable hardened runtime -> NO
 ②: build phase -> denpendenice -> objc
 爽了之后,还来一个 👍  确认一下这几是否OK
