### ISSUE TITLE
Xcode 11.2 无法 调试

### ISSUE THREAD

**Issue by manajay** [LGCooci/objc4_debug#3]
新建 target 需要 关闭 hardened runtime才可以调试 对比你可以调试的配置, 发现了这个解决方案

**Comment by MoonBall** [comment]
> 新建 target 需要 关闭 hardened runtime才可以调试 对比你可以调试的配置, 发现了这个解决方案

It works for me, thanks.

**Comment by LGCooci** [comment]
嗯嗯 这个在我文档上面有说明 ！ 还有最新的Xcode 请更新779
