### ISSUE TITLE
objc4-779.1 , KCObjcTest 中的main.m打断点无效

### ISSUE THREAD

**Issue by Goallying** [LGCooci/objc4_debug#6]
objc4-779.1 , KCObjcTest 中的main.m打断点无效 ，断点被忽略

**Comment by LGCooci** [comment]
因为iOS 新特性影响 请关闭 Enable Hardened Runtime！这里先关闭问题，如还有疑问，可以及时交流

**Comment by NULL-2333** [comment]
还是不行，如果在这个target中添加了自定义类的话main.m中的断点就会失效

**Comment by LGCooci** [comment]
新建类 需要注意build phrase 里面的编译顺序
