### ISSUE TITLE
781运行报错

### ISSUE THREAD

**Issue by Vincentzzg** [LGCooci/objc4_debug#8]
xcode 11.7、系统macOS Big Sur 11.01运行781那个项目报错：
dyld: Symbol not found: _sel_hash
  Referenced from: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
  Expected in: /Users/zhongguangzhou/Library/Developer/Xcode/DerivedData/objc-dcyrbcipeblzjtdkwzjqupppofta/Build/Products/Debug/libobjc.A.dylib
 in /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation

是最新系统的问题吗？

**Comment by LGCooci** [comment]
big sur 并不一定能够使配的！需要测试
